filestash: remove sshd.conf to allow for legacy rsa keys
jquery/infrastructure-puppet pull request #44
Opened 2024-04-23 20:22 UTC by timmywil

- this is no longer needed now that all filestash workflows have been migrated from jenkins to GH actions

2024-04-23 21:18 UTC, mgol approved these changes
Nice!

2024-04-23 22:46 UTC, Krinkle commented
You can safely simulate/stage applying this to a server, by locally using `bin/octodiff-docker.sh` (check docs/puppet.md for how it works, as well as a way to do it without Docker if you prefer).

I expect this to fail compilation because the file is referenced from here:

```puppet
  ssh::server::config { 'filestash':
    source => 'puppet:///modules/profile/filestash/sshd.conf',
  }
```

2024-04-24 14:37 UTC, Krinkle requested changes
Per above comment.

2024-04-24 14:46 UTC, timmywil commented
~I'm working on getting octodiff running on windows.~ I got the image running and will submit a PR.

2024-04-24 15:57 UTC, timmywil commented
I was able to get octodiff up and running and got the expected error, which has now been corrected.

2024-04-24 16:55 UTC, Krinkle approved these changes

2024-04-24 17:33 UTC, merged